Heavy Adornment Memory Optimizations
ROBLOX/Studio-Tools pull request #54
Opened 2016-10-24 06:36 UTC by CloneTrooper1019

Theres some memory consumption problem with the Explorer, that happens when multiple objects are being created and destroyed during each frame. This has been a problem for several months now, but it has become more notable with this plugin, due to the CoreGui suddenly becoming visible in the Explorer.

I updated parts of the Adornment module to utilize a smart object pooling system, so that objects don't have to get cleared and regenerated during each frame. As a side effect, this actually makes the tool faster than it was before, and it can handle large parts without the framerate panicking too much.

2016-10-24 07:47 UTC, DarraghGriffin commented on TransformDragger.rbxmx
> +			for object,expireTime in pairs(queue) do
This isn't too much of an issue but it seems like iterating through the entire queue table every second could be avoided by maintaining the queue in a different way. If you use a queue data structure with fast addition and removal from either end of the queue then you can just check if the top of the queue has an expiration time less than the current tick.

2016-10-24 11:57 UTC, CloneTrooper1019 commented on TransformDragger.rbxmx
> +			for object,expireTime in pairs(queue) do
Good call, I'll update it.

2016-10-27 19:31 UTC, CloneTrooper1019 commented
Bump.

2016-10-27 21:07 UTC, tberg-roblox commented
Sorry, been super busy. I'll try to take a look at this today.

2016-10-27 23:34 UTC, tberg-roblox requested changes
I really like this change. I left a few very minor comments and will pull this into the main branch when resolved.

2016-10-27 23:34 UTC, tberg-roblox commented on TransformDragger.rbxmx
> +	--appendTemporaryLine(Vector3.new(0,0,0), Vector3.new(10, 10, 0), Color3.new(.3,.3,.3), 0.0, 1.5, planeKeeper[1].Adornee)
These comments can be removed

2016-10-27 23:34 UTC, tberg-roblox commented on TransformDragger.rbxmx
> +function recyclingBin:Allocate(objectType,needed,bin)
Please rename bin. It's confusing that we have two objects named the same thing, one containing a table, while the other contains an Instance.

2016-10-27 23:34 UTC, tberg-roblox commented on TransformDragger.rbxmx
> +	bin[class][object] = tick()+expirationTime;
It might be better to pass this in as parameter.

Ignore this: I hadn't seen the new changes.

2016-10-28 02:28 UTC, CloneTrooper1019 commented on TransformDragger.rbxmx
> +	--appendTemporaryLine(Vector3.new(0,0,0), Vector3.new(10, 10, 0), Color3.new(.3,.3,.3), 0.0, 1.5, planeKeeper[1].Adornee)
Got it.

2016-10-28 02:32 UTC, CloneTrooper1019 commented on TransformDragger.rbxmx
> +function recyclingBin:Allocate(objectType,needed,bin)
So just the variable name?
I updated it to be called allocationStorage instead of bin.

2016-10-28 16:10 UTC, tberg-roblox approved these changes

2016-10-28 16:11 UTC, merged